name: Deployment Project  # workflow name
on: push #event - trigger 
jobs:
  test:
    runs-on: ubuntu-latest #runner
    steps:
      - name: Get Code from GitHub Repo
        uses: actions/checkout@v5

      - name: Install Nodejs
        uses: actions/setup-node@v6
        with:
            node-version: 22

      - name: Install dependencies 
        run: |
                cd 02_Starting_Project
                npm install  #npm ci
                npm test
  deploy:
    runs-on: ubuntu-latest #runner
    steps:
      - name: Get Code from GitHub Repo
        uses: actions/checkout@v5

      - name: Install Nodejs
        uses: actions/setup-node@v6
        with:
            node-version: 22

      - name: Install dependencies 
        run: |
                cd 02_Starting_Project
                npm ci
                npm run

      - name: Deploy to Production Server
        run: echo "Deploying to Production Server..."
