name: myworkflow # workflow name
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest #runner
    steps:
      - name: print welcome
        run: echo "Hello, world"

      - name: print Goodbye
        run: |
          echo "byebye",
          echo "section1"
